### ISSUE TITLE
go module name

### ISSUE THREAD

**Issue by dmitris** [davidcoles/vc5#1]
Regarding https://github.com/davidcoles/vc5/blob/master/vc5/go.mod#L1 - I think it would be more idiomatic to put the "FQDN" module name like `github.com/davidcoles/vc5` instead of just `vc5`, and adjust the import paths accordingly.  I would also recommend to consider moving `go.mod` to the repository root (unless you have strong reasons to keep it in subdirectory). The idiomatic module name for example would enable to look up the godoc documentation at the usual place such as https://pkg.go.dev/github.com/davidcoles/vc5

**Comment by davidcoles** [comment]
Hi Dmitry. Yeas, absolutely fair point - I had started this in a very exploratory manner and hadn't really thought of it as a module that would be referred to like that, but the documentation point is something I hadn't considered. Bear with me and I'll ry to rejig it in the near future. Thinking about it, I guess a different frontend could use an aleternative way of periodically getting config (eg. from a disribution URL) rather than a local JSON file. Do let me know if you find the project useful.

**Comment by davidcoles** [comment]
I've done a bit of a re-org now and got rid of the need for the wrapper script.

**Comment by davidcoles** [comment]
Closing
