### ISSUE TITLE
ipv6 support?

### ISSUE THREAD

**Issue by bzed** [davidcoles/vc5#4]
Hi,

we actually though about testing vc5 as it seems to have exactly the features we need, but on the first look there is no ipv6 support at all!? Any plans to support that?

Thanks,
Bernd

**Comment by davidcoles** [comment]
Hello Bernd.

Currently I am following the open-source tradition of scratching my own itch, which right now is replacing layer 2 IPv4 hardware appliances - so that is scope as of the moment.

My thought was that after I have finished replacing the last (and largest) of the services with a software solution then I would look at broadening the scope to IPv6 and layer 3 balancing.

So to directly answer your question; yes, IPv6 support is planned, but it is not a problem that I am currently experiencing myself. I would anticipate that my colleagues will look to taking up IPv6 in the near future so I would be keen to get ahead of the game and hear any perspectives that you have. If you would like to discuss your requirements in more detail do feel free to email me at vc5lb@proton.me - or here if you're happy to.

Thanks for your interest - I hope that it can be of some use to you.

Cheers,
David

**Comment by davidcoles** [comment]
Closing this for now as IPv6 won't be supported until I have implemented reaching backends over layer 3 tunnels.

I have some larger services to migrate to vc5 in the near future and will look into l3 once that is completed.

Thanks
